"""x-router — complexity-based model routing.

Importing this package registers the ``x-router`` algorithm. ``discover.py``
imports it automatically as part of ``import openjiuwen``, so hosts normally do
not import it directly; they call :func:`build_router` to attach configuration.

Design and rationale: see README.md in this directory.
"""

from __future__ import annotations

from .classifier import LocalBackend, backend_from_config
from .bandit import (
    BANDIT_COLD,
    BANDIT_IGNORE,
    BANDIT_OFF,
    BANDIT_OVERRIDE,
    BANDIT_SAME,
    TierEvidence,
    aggregate,
    choose_tier,
    utilities,
)
from .algorithm import (
    RULE_ESCALATE_CLOUD,
    RULE_TARGET_EXCLUDED_DEGRADE,
    RULE_WITHIN_LOCAL_CAPABILITY,
    XRouter,
    decide_by_tier,
    specialize,
)
from .complexity import (
    PROMPT_TEMPLATE,
    SOURCE_HEURISTIC,
    SOURCE_HEURISTIC_FALLBACK,
    SOURCE_LLM,
    SOURCE_PARSE_FAILED,
    SOURCE_UNAVAILABLE,
    build_classifier_request,
    classify,
    classify_heuristic,
    content_text,
    conversation_preview,
    parse_complexity,
)
from .bandit_store import (
    EXTENSION_SCHEMA,
    POLICY_SLOT,
    STORE_BACKEND,
    BanditStore,
    HashedNgramRetriever,
)
from .judge import (
    JUDGE_SYSTEM_PROMPT,
    RUBRIC_WEIGHTS,
    ApiJudgeBackend,
    JudgeBackend,
    JudgeError,
    JudgeRequest,
    LocalJudgeBackend,
    build_judge_request,
    judge_from_config,
    parse_judge_score,
)
from .facade import (
    build_judge,
    build_params,
    build_request,
    build_router,
    build_store,
    build_store_params,
    normalize_messages,
)
from .service import (
    SERVED,
    Scorer,
    XRouterService,
    build_bandit_feedback,
    build_hint,
    build_service,
    parse_reasoning,
    retrieval_text,
)
from .types import (
    BanditParams,
    BanditStoreParams,
    ClassifierRequest,
    ComplexityBackend,
    ComplexityLevel,
    ParamsError,
    XRouterParams,
)

__all__ = [
    "BANDIT_COLD",
    "BANDIT_IGNORE",
    "BANDIT_OFF",
    "BANDIT_OVERRIDE",
    "BANDIT_SAME",
    "BanditParams",
    "BanditStore",
    "BanditStoreParams",
    "ClassifierRequest",
    "EXTENSION_SCHEMA",
    "ApiJudgeBackend",
    "HashedNgramRetriever",
    "JUDGE_SYSTEM_PROMPT",
    "JudgeBackend",
    "JudgeError",
    "JudgeRequest",
    "LocalJudgeBackend",
    "POLICY_SLOT",
    "RUBRIC_WEIGHTS",
    "SERVED",
    "STORE_BACKEND",
    "Scorer",
    "XRouterService",
    "LocalBackend",
    "ComplexityBackend",
    "ComplexityLevel",
    "ParamsError",
    "PROMPT_TEMPLATE",
    "RULE_ESCALATE_CLOUD",
    "RULE_TARGET_EXCLUDED_DEGRADE",
    "RULE_WITHIN_LOCAL_CAPABILITY",
    "SOURCE_HEURISTIC",
    "SOURCE_HEURISTIC_FALLBACK",
    "SOURCE_LLM",
    "SOURCE_PARSE_FAILED",
    "SOURCE_UNAVAILABLE",
    "XRouter",
    "TierEvidence",
    "XRouterParams",
    "aggregate",
    "backend_from_config",
    "build_bandit_feedback",
    "build_hint",
    "build_judge",
    "build_judge_request",
    "build_store",
    "build_store_params",
    "choose_tier",
    "parse_reasoning",
    "retrieval_text",
    "utilities",
    "build_classifier_request",
    "build_params",
    "build_request",
    "build_router",
    "build_service",
    "classify",
    "classify_heuristic",
    "content_text",
    "conversation_preview",
    "decide_by_tier",
    "judge_from_config",
    "normalize_messages",
    "parse_complexity",
    "parse_judge_score",
    "specialize",
]
